### ISSUE TITLE
Game crashes after clicking on the data base entry for the new map and it also gave me a warning to disable the mod because of said map causing an error

### ISSUE THREAD

**Issue by Arthur-The-Ok** [Lehanchic/serpulo-and-erekir-plus#2]
java.lang.NullPointerException
	at mindustry.ctype.UnlockableContent.checkStats(UnlockableContent.java:77)
	at mindustry.ui.dialogs.ContentInfoDialog.show(ContentInfoDialog.java:31)
	at mindustry.ui.dialogs.ModsDialog.lambda$showMod$46(ModsDialog.java:419)
	at arc.scene.Element.lambda$clicked$2(Element.java:913)
	at arc.scene.Element$4.clicked(Element.java:922)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at arc.scene.event.InputListener.handle(InputListener.java:31)
	at arc.scene.Scene.touchUp(Scene.java:370)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:136)
	at arc.input.InputEventQueue.drain(InputEventQueue.java:71)
	at arc.backend.sdl.SdlInput.update(SdlInput.java:181)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:189)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

**Comment by Lehanchic** [comment]
Can you please tell me which map? Well, or make a video where he shows the error. I just couldn't find the map you're talking about.

**Comment by Lehanchic** [comment]
Can you please tell me which map? Well, or make a video where the game shows an error. I just can't find the map you are talking about.

**Comment by Arthur-The-Ok** [comment]
![Captura de tela 2023-03-09 101018](https://user-images.githubusercontent.com/81048660/224033302-f9649731-4e12-41c8-94d8-efad99e6bfa8.png)
![Captura de tela 2023-03-09 101040](https://user-images.githubusercontent.com/81048660/224033327-bdc8d515-35ab-400b-bf12-87987ebbc30b.png)

**Comment by Arthur-The-Ok** [comment]
Wait, now that I'm thinking about it, it's probably because one of the other mods I have (Erekir Extended) also adds a map called omega outpost

**Comment by Lehanchic** [comment]
Oh yea

**Comment by Lehanchic** [comment]
It is

**Comment by Lehanchic** [comment]
I am fix it
